export const SET_PHOTO = 'SET_PHOTO';
export const SET_SIGNUP_INFO = 'SET_SIGNUP_INFO';
export const SET_LOGIN_INFO = 'SET_LOGIN_INFO';
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SET_FACE_LANDMARKS = 'SET_FACE_LANDMARKS';
